### ISSUE TITLE
Setup Yocto Repository

### ISSUE THREAD

**Issue by velascorhwee** [velascorhwee/final-project-assignment-micarray#1]
Create a yocto repository for the project, targetting the Raspberry Pi 4 model b
DoD: Build is successful, able to program image to hardware
Blockers: None

**Comment by velascorboulder** [comment]
![Image](https://github.com/user-attachments/assets/34c26bda-4c1a-4774-9908-f27cfd8e5866)
![Image](https://github.com/user-attachments/assets/2c770535-d6c3-40d8-aaae-5ec685d928c5)

**Comment by velascorhwee** [comment]
https://github.com/cu-ecen-aeld/final-project-velascorboulder/tree/main
