### ISSUE TITLE
Write a c application to stream video from usb webcam

### ISSUE THREAD

**Issue by velascorhwee** [velascorhwee/final-project-assignment-micarray#12]
Write a c application to stream usb camera to hdmi monitor.
DoD: C application should be running and camera captures should be displayed on HDMI monitor attached to Raspberry Pi 4.

**Comment by velascorboulder** [comment]
Was able to accomplish last three sprint tasks in one go. Streaming video form usb cam to hdmi monitor, mic array app running, and text overlay to show gain and DOA.
![Image](https://github.com/user-attachments/assets/c3320808-ad8a-4ab5-837e-a7812ae4d709)
![Image](https://github.com/user-attachments/assets/6bee6a44-0342-4fdc-a90e-ae9c062ee886)
