### ISSUE TITLE
Combine MicArray and Camera applications into one application

### ISSUE THREAD

**Issue by velascorhwee** [velascorhwee/final-project-assignment-micarray#14]

**Comment by velascorboulder** [comment]
Was able to accomplish last three sprint tasks in one go. Streaming video form usb cam to hdmi monitor, mic array app running, and text overlay to show gain and DOA.
https://github.com/velascorhwee/final-project-assignment-micarray/tree/sprint-3-issue-11-12-14
https://github.com/cu-ecen-aeld/final-project-velascorboulder/tree/sprint-3-issue-11-12-14
![Image](https://github.com/user-attachments/assets/c3320808-ad8a-4ab5-837e-a7812ae4d709)
![Image](https://github.com/user-attachments/assets/6bee6a44-0342-4fdc-a90e-ae9c062ee886)
