### ISSUE TITLE
Create startup script

### ISSUE THREAD

**Issue by velascorhwee** [velascorhwee/final-project-assignment-micarray#16]
Create a startup script that will start automatically on boot.
DoD: Application will start up immediately when initial boot process completes.

**Comment by velascorboulder** [comment]
Application starts up on boot up and accepts all keyboard inputs for control
Yocto code
https://github.com/cu-ecen-aeld/final-project-velascorboulder/tree/sprint-3-issue-13

App code
https://github.com/velascorhwee/final-project-assignment-micarray/tree/sprint-3-issue-13
