### ISSUE TITLE
Add Custom Image Layer for Project

### ISSUE THREAD

**Issue by velascorhwee** [velascorhwee/final-project-assignment-micarray#2]
Add a custom image layer for my porject
DoD: Should be able to use bitbake on my custom image i.e. bitbake core-image-rvfinalproj to build image
Blockers: None

**Comment by velascorboulder** [comment]
bitbake aesdproj-image
![Image](https://github.com/user-attachments/assets/e114d1e9-7e11-4eae-82f0-1ec3ff903b16)

**Comment by velascorhwee** [comment]
https://github.com/cu-ecen-aeld/final-project-velascorboulder/tree/main/meta-aesdproj
