### ISSUE TITLE
Modifiy MicArray application to record 5 microphone

### ISSUE THREAD

**Issue by velascorhwee** [velascorhwee/final-project-assignment-micarray#7]
Modify MicArray Application to a multithreading application. It should record audio from the five usb microphones at the same time
DoD: Application should generate five audio files, one for each microphone

**Comment by velascorboulder** [comment]
Yocto:
https://github.com/cu-ecen-aeld/final-project-velascorboulder/tree/sprint-2-issue-7
Application:
https://github.com/velascorhwee/final-project-assignment-micarray/tree/sprint-2-issue-7
![Image](https://github.com/user-attachments/assets/db716bc7-e011-4085-8f50-24410a769b9d)

Here are the audio files as raw data. Import as Raw data into Audacity to listen. Sample Rate = 44100, Encoding: Signed 16bit PCM, Byte Order: Little Endian
[captures.zip](https://github.com/user-attachments/files/17267713/captures.zip)
